version: "3.9"

name: adempiere-grpc-server-stack

services:
  adempiere.db:
    build:
      context: postgresql/
      dockerfile: Dockerfile
    container_name: ${POSTGRES_NAME}
    restart: ${GENERIC_RESTART}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - adempiere_network

  adempiere-grpc-server:
    image: solopcloud/adempiere-backend:alpine-1.7.9
    container_name: ${ADEMPIERE_GRPC_SERVER_HOST}
    restart: ${GENERIC_RESTART}
    ports:
      - 50059
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/50059; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      DB_HOST: ${POSTGRES_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICES_ENABLED: ${SERVICES_ENABLED}
    depends_on:
      adempiere.db:
        condition: service_healthy
    networks:
      - adempiere_network

networks:
  adempiere_network:
    name: ${ADEMPIERE_NETWORK}

volumes:
  volume_postgres:
    name: ${POSTGRES_NETWORK}
