version: "3.9"

networks:
  adempiere-backend:

volumes:
  pgdata:

services:
  adempiere.db:
    image: solopcloud/adempiere-postgres:14-experimental-1.0.5
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=adempiere
      - DB_NAME=adempiere
      - ADEMPIERE_PASSWORD=adempiere
    networks:
      - adempiere-backend

  adempiere.backend:
    image: solopcloud/adempiere-backend
    ports:
      - "50059:50059"
    environment:
      - SERVICES_ENABLED=business; business_partner; core; dashboarding; dictionary; enrollment; file_management; general_ledger; in_out; invoice; issue_management; log; material_management; order; payment; payment_print_export; payroll_action_notice; pos; product; security; store; time_control; ui; user_customization; workflow;
      - DB_HOST=adempiere.db
      - TZ="America/Caracas"
    depends_on:
      - adempiere.db
    networks:
      - adempiere-backend
