version: '3.1'

services:

  database:
    image: solopcloud/adempiere-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=adempiere
      - DB_NAME=adempiere
      - ADEMPIERE_PASSWORD=adempiere

  application:
    image: solopcloud/adempiere-backend
    restart: always
    environment:
      - SERVICES_ENABLED=access; business; core; dashboarding; dictionary; enrollment; general_ledger; log; material_management; ui; workflow; store; pos; business_partner; in_out; invoice; order; payment; payroll_action_notice; product; time_control;
      - DB_HOST=database
    ports:
      - 50059:50059
