# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Project

on:
  push:
    tags:
      - '*'

jobs:

  # TODO: Download .tar and add docker image without uncompress
  # Publish docker alpine image in Docker Hub Registry to application
  push-alpine-imame-dhr:
    name: Push docker alpine image to Docker Hub
    # Skip step based on secret
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: redmine20804v18
#      - name: Download build dist app
#        uses: actions/download-artifact@v3
#        with:
#          path: https://github.com/spuy/backend/archive/refs/tags/redmine20804v18.zip
      - run: pwd
      - run: wget https://github.com/spuy/backend/archive/refs/tags/redmine20804v18.zip
      - run: ls -alh
      - name: Unzip Asset
        run: |
          unzip *.zip -d docker/
      - run: mv docker/redmine20804v18 docker/adempiere-grpc-server
      - run: find .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push alpine image in Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/alpine.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO_ADEMPIERE_GRPC_SERVER }}:alpine
            ${{ secrets.DOCKER_REPO_ADEMPIERE_GRPC_SERVER }}:alpine-${{ github.event.release.tag_name }}
